### PR TITLE
Update _dsboot support for Glauca

### PR DESCRIPTION
**Pull request by TheEnbyperor**
Glauca now supports authenticated bootstrapping with `_dsboot`.

### CODE REVIEW

**Comment by peterthomassen** [comment]
Cool. - As the table gives the impression that its contents are taken from the linked docs at https://docs.glauca.digital/domains/cds/, I suggest updating them as well.

**Comment by TheEnbyperor** [comment]
I pushed this feature out late last night and haven't got round to writing docs on it yet. Writing docs at 11pm probably isn't the best idea.

I'll probably have time to get it sorted today.

**Comment by peterthomassen** [comment]
Sorry, didn't mean to rush.

**Comment by TheEnbyperor** [comment]
I've added some info on it to the docs now.

**Comment by oskar456** [comment]
Thank you!

**Pull request merged**
